name = "BitMasks"
uuid = "a3e06817-fd65-4797-8291-16f435bc2529"
authors = ["Cédric BELMANT"]
version = "0.1.6"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
